### ISSUE TITLE
dynamicHelpers not available in 3.0

### ISSUE THREAD

**Issue by jmls** [JasonGiedymin/express-messages-bootstrap#13]
as dynamicHelpers are not available in 3.0 anymore, how can I use this library ? thanks

**Comment by JasonGiedymin** [comment]
Taking a look at this now

**Comment by jameswyse** [comment]
dynamicHelpers have been replaced with res.locals, I just did the upgrade however now `!= messages()` in jade just outputs a big mess of broken HTML and functions outputting as text..

**Comment by JasonGiedymin** [comment]
I had somethings in the way but I'm positive I'll look at this during the next 24 hours. The problem is I don't always work on bootstrap enough to update. However this is changing, starting next week. I'll be working on several express + bootstrap projects these next months and will be paying more attention. Thanks for your patience!

-Jason

**Comment by jameswyse** [comment]
It seems to be because the returned function isn't run as middleware like dynamicHelpers used to do, to solve this just move the locals to somewhere in your middleware chain and pass in req, res manually.

``` javascript

this.use(function(req, res, next) {
        res.locals = {
            messages:      require('express-messages-bootstrap')(req,res)
        }
}
```

So it works, but we could probably make this tidier..

**Comment by JasonGiedymin** [comment]
Given some of the previous issues and to keep this middleware friendly, I'm re-writing the module. It is roughly 80% complete, easier to use, and allows more custom functionality.

**Comment by JasonGiedymin** [comment]
Complete rewrite sitting in [branch](https://github.com/JasonGiedymin/express-messages-bootstrap/tree/v1.0rc-expressv3)

No longer will render messages unless you do a require().with({...}) AND call upon rmessage() (which is in locals, yes that is an r in front of message).
Otherwise, you have full access to messages in user order (array), i.e. locals.messages.

See tests and fixtures under tests. Sample app is app.js in tests as well.

**Comment by mrmowgli** [comment]
Any chance of getting this branch into npm?

**Comment by JasonGiedymin** [comment]
Will do today

-Jason

**Comment by JasonGiedymin** [comment]
Published.
